spring.application.name=myfoodie

server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/myfoodie

jwt.secret=myfoodie-super-secret-key-for-jwt-token-generation-replace-in-production
jwt.expiration=604800000
